apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yaml -o k8s-kompose/
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: ci-cd-demo
  name: ci-cd-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ci-cd-demo
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f compose.yaml -o k8s-kompose/
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        io.kompose.service: ci-cd-demo
    spec:
      containers:
        - image: REPLACE_IMAGE
          name: ci-cd-demo
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
